### ISSUE TITLE
Sound on new post?

### ISSUE THREAD

**Issue by dheif** [flytaly/reddit-post-notifier#11]
Hi,

Could the extension make a sound when there's a new post? I realize I don't watch the browser's tray often and miss new posts.

**Comment by dheif** [comment]
To give more context, I'm using it to see posts about graphic cards that are in stock (so I need to be fast when there's a new one).

**Comment by flytaly** [comment]
I guess you are using Chrome? Because in Firefox you can install [notification-sound addon](https://addons.mozilla.org/ru/firefox/addon/notification-sound/). It should work with this extension.

Also, do you select these checkboxes to receive notifications?
![Screenshot 2020-11-28 at 05 06 06](https://user-images.githubusercontent.com/1577569/100491776-6d33b680-3137-11eb-85b4-f6adaa0a722b.png)
![Screenshot 2020-11-28 at 05 05 37](https://user-images.githubusercontent.com/1577569/100491765-5d1bd700-3137-11eb-963d-6225ea47f938.png)

Anyway, I've added some sounds that you can enable in the next version 3.1.0. It should be available in the Chrome store after review (around 1 day usually).
![Screenshot 2020-11-28 at 05 08 52](https://user-images.githubusercontent.com/1577569/100491827-d0254d80-3137-11eb-9e9d-eb72abb8096b.png)
You still will need to select the checkboxes that I have mentioned above to play sound.

**Comment by dheif** [comment]
Exactly, I'm on Chrome.

I've also checked the Desktop notifications, but don't see anything popping. I'll check if it's because my Windows notifications are set to Alarms only or anything like that.

Thank you very much for adding the sound! 👍
