### ISSUE TITLE
New version missing something

### ISSUE THREAD

**Issue by siffegh** [flytaly/reddit-post-notifier#20]
What happened to being able to open all private mail at once?
![Screenshot_1](https://user-images.githubusercontent.com/18728013/147811292-0950d9ba-49c5-4c9d-a462-96b38ca99f66.jpg)

**Comment by flytaly** [comment]
It was removed because there is support for multiple accounts. Now you can open messages after authentication, clicking on the icon

![popup](https://user-images.githubusercontent.com/1577569/147817402-6550c953-3bc8-484f-ab80-22ae3d725338.png)

It just opens `reddit.com/message/unread` like the previous mail icon in the header.

But if you need that old inbox button, I can restore it.

**Comment by siffegh** [comment]
Thanks, here's what I'd like. Can be done with the new version:

- new option: open 'All' when clicking the 'open in new tab' icon (which is what the prior version did when clicking the envelope)

- new option: upon clicking the 'open in new tab' icon, clear the list and icon number and close the popup

**Comment by flytaly** [comment]
Added in v4.1.0.

**Comment by siffegh** [comment]
Perfect - thanks very much!
