### ISSUE TITLE
Stopped working today:  Couldn't fetch messages: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by uj** [flytaly/reddit-post-notifier#23]
Stopped working today, newest version.

Couldn't fetch messages: Unexpected token < in JSON at position 0

I also re-authorized, still the same error message.

**Comment by flytaly** [comment]
It is more on Reddit's side. 

I also had it a moment ago, but now it works.  You can test with the following URL (if you are logged in): 
https://www.reddit.com/message/unread.json?raw_json=1 
It should return JSON data `{kind : "Listing", ...`.

It was down for some time today and returned text with error 504 instead of JSON data. The extension tried to parse it and failed.

I should probably update the message in the extension to a less confusing one.
