### ISSUE TITLE
Is it possible to Monitor one specific Reddit post?

### ISSUE THREAD

**Issue by missiah** [flytaly/reddit-post-notifier#27]
Is there a setting in the Extension so i can Monitor only one specific post for new Updates?

**Comment by flytaly** [comment]
No, unfortunately.

It's not easy to implement robust thread notifier.  Reddit has some limitations caused by legacy code. You can't just ask Reddit to return every new comments in a post.  

You can use RSS as a workaround, though, but it seems it's not reliable. Read more in [this thread](https://github.com/flytaly/reddit-post-notifier/issues/6).

**Comment by missiah** [comment]
ok thank you for the quick respond
