### ISSUE TITLE
Possible to fetch new chat messages?

### ISSUE THREAD

**Issue by Akshat-h** [flytaly/reddit-post-notifier#48]
Hay! 
it's me again with another feature request. 

Currently, the extension fetches new messages from other accounts and works without issues. 
But it does not fetch messages from the New Reddit chat.  

So is there any possibility of adding this feature?

Thanks a bunch,

**Comment by flytaly** [comment]
Unfortunately, it's practically impossible. I mean, there is a way, but it would require a lot of reverse-engineering, and the end result would likely not be reliable and probably would violate some Reddit policies.

It's all because Reddit [doesn't provide a public API for chat](https://www.reddit.com/r/redditdev/comments/17s83sf/comment/k8o5cow/?context=3).

![image](https://github.com/flytaly/reddit-post-notifier/assets/1577569/f7910a51-575e-46fa-88af-1812c221bfa7)

**Comment by Akshat-h** [comment]
Well, that's a bummer.

**Comment by Akshat-h** [comment]
Not Feasible!
